name       : haskell-exceptions
version    : 0.10.4
release    : 3
source     :
    - https://hackage.haskell.org/package/exceptions-0.10.4/exceptions-0.10.4.tar.gz : 4d0bfb4355cffcd67d300811df9d5fe44ea3594ed63750795bfc1f797abd84cf
license    : BSD-3-Clause
component  : programming.haskell
summary    : Extensible optionally-pure exceptions
description: |
    Extensible optionally-pure exceptions
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
