name       : haskell-exceptions
version    : 0.10.0
release    : 2
source     :
    - https://hackage.haskell.org/package/exceptions-0.10.0/exceptions-0.10.0.tar.gz : 1edd912e5ea5cbda37941b06738597d35214dc247d332b1bfffc82adadfa49d7
license    : BSD-3-Clause
component  : programming.haskell
summary    : Extensible optionally-pure exceptions
description: |
    Extensible optionally-pure exceptions
builddeps  :
    - haskell-cabal-install
    - haskell-mtl
    - haskell-stm
    - haskell-transformers-compat
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
