name       : haskell-exceptions
version    : 0.8.3
release    : 1
source     :
    - http://hackage.haskell.org/package/exceptions-0.8.3/exceptions-0.8.3.tar.gz : 4d6ad97e8e3d5dc6ce9ae68a469dc2fd3f66e9d312bc6faa7ab162eddcef87be
license    : BSD-3-Clause
component  : programming.haskell
summary    : Extensible optionally-pure exceptions
description: |
    Extensible optionally-pure exceptions
builddeps  :
    - haskell-cabal-install
    - haskell-transformers-compat
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
